version: '3'

services:
    djangoapi:
        container_name: djangoapi
        build: 
          context: .
        ports:
          - "8000:8000"
        volumes: 
          - ./app:/app
        command: >
          sh -c "python manage.py wait_for_db && 
          python manage.py migrate &&
          python manage.py runserver 0.0.0.0:8000"
        environment: 
          - DB_HOST=postdb
          - DB_NAME=djangoapi
          - DB_USER=postgres
          - DB_PASS=secret
        depends_on: 
          - postdb
    postdb:
        image: postgres:alpine
        environment: 
          - POSTGRES_DB=djangoapi
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=secret
